# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Examples',
            new_name='Example',
        ),
        migrations.RenameModel(
            old_name='Musicians',
            new_name='Musician',
        ),
    ]
