# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayit', '0004_delete_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='musicians/'),
        ),
    ]
