# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayit', '0005_musician_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='examples/'),
        ),
        migrations.AddField(
            model_name='example',
            name='media_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
