# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayit', '0006_auto_20170127_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='audio_image',
            field=models.ImageField(blank=True, null=True, upload_to='examples/'),
        ),
    ]
